name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: docker build . -t udm-heat

      - name: Test - nothing should run
        run: docker run -v $PWD/data:/data -t udm-heat

      - name: Test - run population and dwellings without demographic break
        run: docker run -v $PWD/data:/data --env calculate_new_population=True --env demographic_breakdown=False --env new_dwelling_totals=True --env include_northern_ireland=True --env rcm_population_outputs=True --env adjust_population_baseline=True -t udm-heat

      #- name: Test - run everything
      #  run: docker run -v $PWD/data:/data --env calculate_new_population=True --env demographic_breakdown=True --env new_dwelling_totals=True --env include_northern_ireland=True --env rcm_population_outputs=True --env adjust_population_baseline=True -t udm-heat

      - name: Test - run everything without the pph file and demographic breakdown
        run: docker run -v $PWD/data:/data --env calculate_new_population=True --env demographic_breakdown=False --env new_dwelling_totals=True --env include_northern_ireland=True --env rcm_population_outputs=True --env adjust_population_baseline=True -t udm-heat
